export const TempData=[
    {
        "imageUrl": "https://images.pexels.com/photos/3889624/pexels-photo-3889624.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
        "brand": "Louis Philippe",
        "title": "Checks Shirt",
        "color": "Blue",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/17739013/pexels-photo-17739013/free-photo-of-man-wearing-shirt-by-the-lake.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Giorgio Armani",
        "title": "Plain Shirt",
        "color": "White",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/5145180/pexels-photo-5145180.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Gucci",
        "title": "Green Shirt",
        "color": "Green",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/769733/pexels-photo-769733.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Louis Philippe",
        "title": "Checks Shirt",
        "color": "Red",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/1232459/pexels-photo-1232459.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Tommy Hilfiger",
        "title": "Plain T-Shirt",
        "color": "Blue",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/1043148/pexels-photo-1043148.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Balenciaga",
        "title": "Cotton Shirt",
        "color": "Light Blue",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/4287123/pexels-photo-4287123.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Denim",
        "title": "Jeans Shirt",
        "color": "Blue",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/6649009/pexels-photo-6649009.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Versace",
        "title": "Shirt",
        "color": "Dark Green",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/12730638/pexels-photo-12730638.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Freedom",
        "title": "Stripes T-Shirt",
        "color": "Black",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    },
    {
        "imageUrl": "https://images.pexels.com/photos/6000520/pexels-photo-6000520.jpeg?auto=compress&cs=tinysrgb&w=600",
        "brand": "Ferdie Balean",
        "title": "Spiderman T-Shirt",
        "color": "Red",
        "discountedPrice": "",
        "price": "",
        "discountPercent": "",
        "size": [],
        "quantity": "",
        "topLevelCategory": "",
        "secondLevelCategory": "",
        "thirdLevelCategory": "",
        "description": ""
    }
]